class_name GlobalEnums

# order HAVE to be the same as in Audio
enum BUS{MASTER, MUSIC, SFX, UI}
enum PAUSE_REASON{PAUSE, FAILED}
enum TERRA_VARIBLE_TYPE{ATMOSPHERE, OXYGEN, HEAT}
enum POP_UP {SETTINGS, CREDITS, PAUSE}
#enum SLOW_ACTION {BACTERIA, ALGEA}
